"""Playwright project detection and ephemeral scaffolding.

For bare specs, 9lives creates the minimal bundle `npx playwright test` needs:
the spec, a Playwright config, and a package.json.
"""

import json
import logging
import shutil
from pathlib import Path

logger = logging.getLogger(__name__)

PLAYWRIGHT_VERSION = "1.61.1"

CONFIG_JS = """\
// Generated by 9lives — https://9lives.run
const { defineConfig } = require('@playwright/test');

// NINELIVES_CHROMIUM_PATH lets CI images with a preinstalled browser skip
// `playwright install` entirely (version-mismatch escape hatch).
const executablePath = process.env.NINELIVES_CHROMIUM_PATH || undefined;

module.exports = defineConfig({
  timeout: 30000,
  retries: 0,
  reporter: [['json', { outputFile: 'results.json' }], ['line']],
  use: {
    headless: true,
    viewport: { width: 1280, height: 720 },
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'retain-on-failure',
    launchOptions: executablePath ? { executablePath } : {},
  },
  projects: [{ name: 'chromium', use: { browserName: 'chromium' } }],
});
"""


def find_user_project(start: Path) -> Path | None:
    """Walk up from `start` looking for a package.json that depends on @playwright/test."""
    for directory in [start, *start.parents]:
        package_json = directory / "package.json"
        if package_json.is_file():
            try:
                data = json.loads(package_json.read_text())
            except (OSError, json.JSONDecodeError):
                continue
            deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
            if "@playwright/test" in deps:
                return directory
    return None


def find_enclosing_package_json(start: Path) -> Path | None:
    """Nearest ancestor dir (incl. `start`) with a package.json, regardless of its deps.

    Used to tell a bare spec (no package.json anywhere → safe to scaffold) apart from
    a spec inside a real Node project that simply hasn't installed @playwright/test.
    """
    for directory in [start, *start.parents]:
        if (directory / "package.json").is_file():
            return directory
    return None


def scaffold_project(workdir: Path, spec_path: Path) -> Path:
    """Create an ephemeral Playwright project around a bare spec file.

    Returns the project directory; the spec is copied in under its own name.
    """
    workdir.mkdir(parents=True, exist_ok=True)

    package_json = {
        "name": "ninelives-run",
        "version": "1.0.0",
        "private": True,
        "scripts": {"test": "npx playwright test"},
        "devDependencies": {"@playwright/test": PLAYWRIGHT_VERSION},
    }
    (workdir / "package.json").write_text(json.dumps(package_json, indent=2))
    (workdir / "playwright.config.js").write_text(CONFIG_JS)
    shutil.copy2(spec_path, workdir / spec_path.name)

    logger.info("Scaffolded ephemeral Playwright project at %s", workdir)
    return workdir
